package ru.itmo.wp.model.repository.impl;

import ru.itmo.wp.model.database.DatabaseUtils;
import ru.itmo.wp.model.domain.Event;
import ru.itmo.wp.model.exception.RepositoryException;
import ru.itmo.wp.model.repository.EventRepository;

import javax.sql.DataSource;
import java.sql.*;

public class EventRepositoryImpl implements EventRepository {
    private final DataSource DATA_SOURCE = DatabaseUtils.getDataSource();

    @Override
    public void save(Event event) {
        try (Connection connection = DATA_SOURCE.getConnection()) {
            String sqlRequest;
            if (event.getType() == Event.Type.ENTER) {
                sqlRequest = "INSERT INTO `Event` (`userId`, `type`, `creationTime`) VALUES (?, 'ENTER', NOW())";
            } else {
                sqlRequest = "INSERT INTO `Event` (`userId`, `type`, `creationTime`) VALUES (?, 'LOGOUT', NOW())";
            }
            try (PreparedStatement statement = connection.prepareStatement(
                    sqlRequest,
                    Statement.RETURN_GENERATED_KEYS
            )) {
                statement.setLong(1, event.getUserId());
                if (statement.executeUpdate() != 1) {
                    throw new RepositoryException("Can't save event.");
                } else {
                    ResultSet generatedKeys = statement.getGeneratedKeys();
                    if (generatedKeys.next()) {
                        event.setId(generatedKeys.getLong(1));
                        event.setCreationTime(find(event.getId()).getCreationTime());
                    } else {
                        throw new RepositoryException("Can't save Event [no autogenerated keys]");
                    }
                }

            }
        } catch (SQLException e) {
            throw new RepositoryException("Can't save event.", e);
        }
    }

    private Event find(long id) {
        try (Connection connection = DATA_SOURCE.getConnection()) {
            try (PreparedStatement statement = connection.prepareStatement("SELECT * FROM Event WHERE id=?")) {
                statement.setLong(1, id);
                try (ResultSet resultSet = statement.executeQuery()) {
                    return toEvent(statement.getMetaData(), resultSet);
                }
            }
        } catch (SQLException e) {
            throw new RepositoryException("Can't find Event.", e);
        }
    }

    private Event toEvent(ResultSetMetaData metaData, ResultSet resultSet) throws SQLException {
        if (!resultSet.next()) {
            return null;
        }

        Event event = new Event();
        for (int i = 1; i <= metaData.getColumnCount(); i++) {
            switch (metaData.getColumnName(i)) {
                case "id":
                    event.setId(resultSet.getLong(i));
                    break;
                case "userId":
                    event.setUserId(resultSet.getLong(i));
                    break;
                case "type":
                    String type = (String) resultSet.getObject(i);
                    if (type.equals("ENTER")) {
                        event.setType(Event.Type.ENTER);
                    } else {
                        event.setType(Event.Type.LOGOUT);
                    }
                    break;
                case "creationTime":
                    event.setCreationTime(resultSet.getTimestamp(i));
                    break;
                default:
                    // No operations.
            }
        }
        return event;
    }

}
